language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "pypy"
  - "pypy3"
env:
  - DJANGO="Django>=1.4,<1.5"
  - DJANGO="Django>=1.5,<1.6"
  - DJANGO="Django>=1.6,<1.7"
  - DJANGO="Django>=1.7,<1.8"
install:
  - travis_retry pip install -q $DJANGO
  - pip install py-dateutil
  - python setup.py develop
script: python manage.py test rest_framework_filters

matrix:
  exclude:
    - python: "3.2"
      env: DJANGO="Django>=1.4,<1.5"
    - python: "3.3"
      env: DJANGO="Django>=1.4,<1.5"
    - python: "3.4"
      env: DJANGO="Django>=1.4,<1.5"
    - python: "pypy"
      env: DJANGO="Django>=1.4,<1.5"
    - python: "pypy3"
      env: DJANGO="Django>=1.4,<1.5"
    - python: "2.6"
      env: DJANGO="Django>=1.7,<1.8"
  fast_finish: true
